load("//tools/bazel_extensions:tests.bzl", "java_test_suite")

java_test_suite(
    name = "unit",
    srcs = glob(["*Test.java"]),
    package = "com.corp.util.function",
    deps = [
        "//src/com/corp/util/function",
    ]
)
